### ISSUE TITLE
Buggy implementation of smooth L1 loss

### ISSUE THREAD

**Issue by flovst** [trzy/FasterRCNN#2]
The implementation in `pytorch/model/detector/regression_loss (line 144)` seems to apply x (instead of x_abs) in the case selection.
Simply changing `is_negative_branch = (x < (1.0 / sigma_squared))` to `is_negative_branch = (x_abs ...).` shall fix it.

Thank you for this project!

**Comment by trzy** [comment]
Good eye, thank you! Fixed.
