### ISSUE TITLE
What shoud be structute of dataset dir?

### ISSUE THREAD

**Issue by palandlom** [trzy/FasterRCNN#5]
Noted dataset `VOC2007` contains of the following folders:
```bash
Annotations  
ImageSets  
JPEGImages  
SegmentationClass  
SegmentationObject
```
Are they all necessary OR only some of them should be provided?

**Comment by trzy** [comment]
Check out voc.py — it describes which directories need to be present. Only the first three and not the last two. If you have a custom dataset you’ll need to structure it in this format or write a new dataset loader to replace what’s in voc.py.
