### ISSUE TITLE
Usage over Object Detection APi

### ISSUE THREAD

**Issue by heidrian-eth** [trzy/FasterRCNN#6]
Hi, could you please provide some advice over using this approach versus using a Faster R CNN model with the Tensorflow Object Detection API?

Thanks, you did a great job.

**Comment by trzy** [comment]
This repo is really intended more for educational purposes or to build off of than to deploy for practical applications. I believe the built in models are likely to be more performant, easier to integrate into projects, and easier to train on custom data.

Instructions on how to run my model are present in the README.md.

**Comment by adrian-pipolhub** [comment]
Thanks for clarifying. Very useful as a first approach, indeed.
