### ISSUE TITLE
Sample larger than population or is negative during counting of negative_anchor_idxs

### ISSUE THREAD

**Issue by palandlom** [trzy/FasterRCNN#7]
I have error:
```
Sample larger than population or is negative
```
in `FasterRCNN\models\faster_rcnn.py` in this section

```python
  # Sample, producing indices into the index maps
    num_positive_anchors = len(positive_anchors)
    num_negative_anchors = len(negative_anchors)
    num_positive_samples = min(self._rpn_minibatch_size // 2, num_positive_anchors) # up to half the samples should be positive, if possible
    num_negative_samples = self._rpn_minibatch_size - num_positive_samples          # the rest should be negative
    positive_anchor_idxs = random.sample(range(num_positive_anchors), num_positive_samples)
    # negative_anchor_idxs = random.sample(range(num_negative_anchors), num_negative_samples)  # <-- error is here
    
    # ... fixed by
    negative_anchor_idxs = random.sample(range(num_negative_anchors), min(num_negative_samples, num_negative_anchors)) 
```
+
I have specific dataset with only 1 class and there are no negative samples (images that do not contain objects on this class)

Is this the correct fix? Or is it better to add negative examples into the dataset.

**Comment by trzy** [comment]
I'm not sure how you found yourself in this situation. You don't necessarily need negative sample images. Every image will have negative samples (anchors that do not sufficiently overlap with an object box); the negative samples are generated automatically and are not manually labeled. There *must* be a background (no object) class, class 0, in addition to your single object class.

Faster-RCNN basically works as follows during training:

- A series of points is overlaid in image space, 16 pixels apart in each dimension. These are the center of the so-called "anchor" boxes. Each of these points is the center of several anchors of different sizes. 
- Given object boxes from the data set, the function generate_rpn_map() in anchors.py produces a big map of all the anchors, including whether each anchor is an object anchor or not. Object anchors are those whose anchor box overlaps the actual object box sufficiently (IoU >= 0.7). This is where negative anchor "samples" are first defined.
- For each "object anchor", regression targets for the corresponding object box are computed. Remember that the region proposal network will output a bunch of boxes that are thought to contain any object (doesn't matter which) along with a bounding box that is expressed as a modification of the corresponding anchor. We perform some post processing to convert that into absolute pixel coordinates (y1, x1, y2, x2) of two of the corners.
- During training and inference, the RPN network predicts "object" boxes -- boxes thought to contain one of the non-background object classes. These may be entirely incorrect and RPN generates a large number of proposals, many of which are wrong.
- During training only, we can compare the proposal boxes with the actual object boxes and based on an IoU threshold (0.5), we assign proposals to their corresponding object class or "background" (no object). This is used to train the detector.
- The detector takes proposals and determines which object class (including "background") they belong to and spits out regression targets for modifying the proposal box into the actual final box.

Hope that makes sense. I'm not sure where you're going wrong but you should definitely *not* modify the code as you did. You also should not need to manually create negative samples. In your case you will have two classes: background and your object.

I'm actually curious as to whether you even need the detector stage if you have only a single class. May be worth trying with and without,.

**Comment by trzy** [comment]
Looking at your code carefully, maybe your change is reasonable. What are the actual values for negative/positive anchors and negative/positive samples? And why are there so few negative samples? Are your boxes extremely large, encompassing most of the image? The RPN mini-batch should be pretty small compared to the total number of anchors. That minus the number of positive anchors (which is clamped to be no larger than 0.5 * mini batch size) is the number of negative anchors we sample, and there should certainly be enough of those. 

It seems technically possible to encounter your situation but I'm inclined to think the problem is elsewhere and that this is a good sign something is up with the labeling.

EDIT: Deleted my previous comment. You do not need to provide negative samples because these are computed automatically during training from anchors that do not overlap your object boxes. This makes me wonder what your object boxes look like.

**Comment by palandlom** [comment]
Thank for detailed explanation. 
I used this dataset 
https://www.kaggle.com/datasets/aubird/au-bird-scene-photo-collection

with conversion to VOC2007 format by converter. I used this notebook to download and convert dataset
https://colab.research.google.com/drive/1cEl5zM6ruw9jFqyjfGT_2YcpEJb3OdKX?hl=ru#scrollTo=53b7REmruhlz

> Are your boxes extremely large, encompassing most of the image?

It seems possible - some images contain >10 birds

> is a good sign something is up with the labeling.

I expect that we will create our own dataset in next few mouth so I'll take this into account and let you know
